[phases.setup]
nixPkgs = ['openjdk17']

[phases.build]
cmds = [
  "mkdir -p app/lib",
  "cp lib/*.jar app/lib",
  "javac -cp 'app/lib/*' -d app *.java",
  "find app"
]

[start]
cmd = "java -cp 'app:app/lib/*' MyServlet"